version: '3.7'
services: 
    database:
        container_name: "database"
        image: postgres
        env_file: 
            - .env
        ports: 
            - "5432:5432"
        volumes: 
            - database-data:/var/lib/postgresql/data/
    cache:
        container_name: "cache"
        image: bitnami/redis
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
        ports: 
            - "6379:6379"
        volumes: 
            - cache-data:/bitnami/redis/data
    lavalink:
        container_name: "lavalink"
        image: fredboat/lavalink:dev
        ports: 
            - "2333:2333"
        volumes: 
            - ./application.yml:/opt/Lavalink/application.yml
    cubot:
        container_name: "cubot"
        build: .
        depends_on: 
            - database
            - cache
            - lavalink
        network_mode: host
        env_file: 
            - .env
volumes:
    database-data:
    cache-data: